### ISSUE TITLE
Feature Request: Add timestamps

### ISSUE THREAD

**Issue by candideu** [briansunter/logseq-get-youtube-captions#6]
Hello! Thank you for making this wonderful plugin! It really helps with searching things up

My suggestion would be to have the option of automatically getting the timestamps for the transcript, so that a person can jump to a certain point in the video

**Comment by briansunter** [comment]
Thank you for the feedback. I definitely will implement this. The API gives me the timestamps so should be relatively straightforward.

**Comment by briansunter** [comment]
Added in #8 Let me know what you think!

**Comment by candideu** [comment]
> Added in #8 Let me know what you think!

Looking good @briansunter !! 🚀 Thank you for implementing this feature!

My only other suggestion would be to add an option for chapters. So when someone right-clicks on the video block, there could be "get-youtube-captions" _and_ "get-youtube-chapters" (if applicable).
