### ISSUE TITLE
Large block will not be editable or searchable to not slow down the app, please use another editor to edit this block.

### ISSUE THREAD

**Issue by Victor239** [briansunter/logseq-get-youtube-captions#7]
Getting this error when I use your plugin with [this video](https://www.youtube.com/watch?v=Xy9ZXRRgpLk): 

![](https://i.imgur.com/qTwNIUq.png)

I think your plugin needs to insert captions as multiple blocks if it's a high length.

Logseq v0.8.10

**Comment by briansunter** [comment]
Added in #8 let me know what you think!
